services:
  db:
    image: postgis/postgis:18-3.6
    container_name: ddemachim-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: ddemachim
    ports:
      - "5432:5432"
    volumes:
      - ddemachim-db-data:/var/lib/postgresql

  redis:
    image: redis:8.8.0-alpine
    container_name: ddemachim-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ddemachim-redis-data:/data

volumes:
  ddemachim-db-data:
  ddemachim-redis-data:
