package com.ddemachim.server.domain.crowding.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.ddemachim.server.domain.crowding.entity.CrowdingGrid;
import jakarta.persistence.EntityManager;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.Polygon;
import org.locationtech.jts.geom.PrecisionModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class CrowdingGridRepositoryTest {

    private static final GeometryFactory GEOMETRY_FACTORY =
            new GeometryFactory(new PrecisionModel(), 4326);

    @Autowired
    private CrowdingGridRepository crowdingGridRepository;

    @Autowired
    private EntityManager entityManager;

    @BeforeEach
    void registerH2SpatialFunctions() {
        entityManager.createNativeQuery(
                        """
                        CREATE TABLE IF NOT EXISTS crowding_grid (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            grid_code VARCHAR(64) NOT NULL UNIQUE,
                            grid_x INTEGER NOT NULL,
                            grid_y INTEGER NOT NULL,
                            geometry GEOMETRY NOT NULL,
                            center_latitude DOUBLE PRECISION NOT NULL,
                            center_longitude DOUBLE PRECISION NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            CONSTRAINT uq_crowding_grid_xy UNIQUE (grid_x, grid_y)
                        )
                        """)
                .executeUpdate();
        entityManager.createNativeQuery(
                        "CREATE ALIAS IF NOT EXISTS ST_MAKEENVELOPE FOR '"
                                + H2SpatialFunctions.class.getName()
                                + ".makeEnvelope'")
                .executeUpdate();
        entityManager.createNativeQuery(
                        "CREATE ALIAS IF NOT EXISTS ST_INTERSECTS FOR '"
                                + H2SpatialFunctions.class.getName()
                                + ".intersects'")
                .executeUpdate();
    }

    @Test
    void findIntersectingBoundsReturnsOnlyPolygonsTouchingTheEnvelope() {
        crowdingGridRepository.saveAll(List.of(
                grid("G-100-100", 100, 100, polygon(126.970, 37.570, 126.980, 37.580)),
                grid("G-101-100", 101, 100, polygon(127.000, 37.570, 127.010, 37.580))));
        entityManager.flush();
        entityManager.clear();

        List<CrowdingGrid> result = crowdingGridRepository.findIntersectingBounds(
                37.569,
                37.581,
                126.969,
                126.981,
                10);

        assertThat(result)
                .extracting(CrowdingGrid::getGridCode)
                .containsExactly("G-100-100");
    }

    private static CrowdingGrid grid(
            String gridCode,
            int gridX,
            int gridY,
            Polygon polygon) {
        return CrowdingGrid.create(
                gridCode,
                gridX,
                gridY,
                polygon,
                polygon.getCentroid().getY(),
                polygon.getCentroid().getX());
    }

    private static Polygon polygon(
            double minLongitude,
            double minLatitude,
            double maxLongitude,
            double maxLatitude) {
        return H2SpatialFunctions.makeEnvelope(
                minLongitude,
                minLatitude,
                maxLongitude,
                maxLatitude,
                4326);
    }

    public static final class H2SpatialFunctions {

        private H2SpatialFunctions() {
        }

        public static Polygon makeEnvelope(
                double minLongitude,
                double minLatitude,
                double maxLongitude,
                double maxLatitude,
                int srid) {
            GeometryFactory geometryFactory = new GeometryFactory(new PrecisionModel(), srid);
            return geometryFactory.createPolygon(new Coordinate[] {
                new Coordinate(minLongitude, minLatitude),
                new Coordinate(maxLongitude, minLatitude),
                new Coordinate(maxLongitude, maxLatitude),
                new Coordinate(minLongitude, maxLatitude),
                new Coordinate(minLongitude, minLatitude)
            });
        }

        public static boolean intersects(Geometry left, Geometry right) {
            return left.intersects(right);
        }
    }
}
