-- Additive, repeatable columns for Naver API HUB Search Trend re-evaluation.
-- Values are relative search-interest indices, never absolute search volume.
ALTER TABLE place_trend_snapshot
    ADD COLUMN IF NOT EXISTS trend_status varchar(30),
    ADD COLUMN IF NOT EXISTS short_ratio double precision,
    ADD COLUMN IF NOT EXISTS six_month_ratio double precision,
    ADD COLUMN IF NOT EXISTS recent_search_interest_average double precision,
    ADD COLUMN IF NOT EXISTS previous_14d_search_interest_average double precision,
    ADD COLUMN IF NOT EXISTS six_month_baseline_search_interest_average double precision,
    ADD COLUMN IF NOT EXISTS recent_valid_observation_days integer,
    ADD COLUMN IF NOT EXISTS previous_valid_observation_days integer,
    ADD COLUMN IF NOT EXISTS six_month_baseline_valid_observation_days integer,
    ADD COLUMN IF NOT EXISTS trend_source varchar(80),
    ADD COLUMN IF NOT EXISTS trend_recent_start date,
    ADD COLUMN IF NOT EXISTS trend_recent_end date,
    ADD COLUMN IF NOT EXISTS trend_previous_start date,
    ADD COLUMN IF NOT EXISTS trend_previous_end date,
    ADD COLUMN IF NOT EXISTS trend_baseline_start date,
    ADD COLUMN IF NOT EXISTS trend_baseline_end date,
    ADD COLUMN IF NOT EXISTS trend_time_unit varchar(10),
    ADD COLUMN IF NOT EXISTS trend_baseline_months integer,
    ADD COLUMN IF NOT EXISTS trend_comparison_label varchar(120),
    ADD COLUMN IF NOT EXISTS trend_current_month varchar(7),
    ADD COLUMN IF NOT EXISTS trend_current_month_ratio double precision,
    ADD COLUMN IF NOT EXISTS trend_current_value double precision,
    ADD COLUMN IF NOT EXISTS trend_baseline_value double precision,
    ADD COLUMN IF NOT EXISTS monthly_ratio double precision,
    ADD COLUMN IF NOT EXISTS trend_partial_month_adjusted boolean,
    ADD COLUMN IF NOT EXISTS trend_partial_month_days_used integer,
    ADD COLUMN IF NOT EXISTS trend_month_values jsonb,
    ADD COLUMN IF NOT EXISTS trend_missing_months text[];
