-- Retired compatibility filename.
-- Relative mention evidence is no longer persisted in the database.
-- The final place_trend_result contract stores only frontend Search Trend
-- metrics; use migrate_simplify_blog_trend_persistence.sql for existing DBs.
