-- Retired compatibility filename.
-- Search Trend metrics are part of place_trend_result; apply
-- add_blog_trend_tables.sql or migrate_simplify_blog_trend_persistence.sql.
-- No ALTER TABLE is intentionally performed here because the old snapshot
-- table was removed from the persistence contract.
