-- Superseded by migrate_simplify_blog_trend_persistence.sql.
-- Kept as a historical compatibility filename; the complete, scoped trend
-- table cleanup must be applied through the simplification migration.
