CREATE TABLE IF NOT EXISTS place_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    label_ko VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    normalized_name VARCHAR(200) NOT NULL,
    category_id BIGINT,
    road_address VARCHAR(1000),
    lot_address VARCHAR(1000),
    district VARCHAR(30),
    neighborhood VARCHAR(30),
    location VARBINARY,
    phone VARCHAR(50),
    website VARCHAR(1000),
    description VARCHAR(4000),
    image_url VARCHAR(4000),
    image_source VARCHAR(30),
    image_attribution VARCHAR(4000),
    operating_hours_raw VARCHAR(4000),
    operating_days_raw VARCHAR(4000),
    closed_days_raw VARCHAR(4000),
    transit_info VARCHAR(4000),
    accessibility VARCHAR(4000),
    tags VARCHAR ARRAY,
    default_dwell_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS blog_trend_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_week DATE NOT NULL,
    status VARCHAR(10) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    processed_place_count INTEGER NOT NULL DEFAULT 0,
    result_count INTEGER NOT NULL DEFAULT 0,
    failure_reason VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_blog_trend_run_week UNIQUE (run_week)
);

CREATE TABLE IF NOT EXISTS place_trend_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    recent_interest_average DOUBLE,
    previous_interest_average DOUBLE,
    interest_change_percent DOUBLE,
    measured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_place_trend_result_run_place UNIQUE (run_id, place_id),
    CONSTRAINT fk_place_trend_result_run FOREIGN KEY (run_id) REFERENCES blog_trend_run(id),
    CONSTRAINT fk_place_trend_result_place FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE IF NOT EXISTS filming_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    content_type VARCHAR(30),
    match_status VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS place_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    name VARCHAR(200),
    price INTEGER,
    description VARCHAR(1000),
    image_url VARCHAR(4000)
);
