CREATE TABLE IF NOT EXISTS place_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    label_ko VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    normalized_name VARCHAR(200) NOT NULL,
    category_id BIGINT,
    road_address VARCHAR(1000),
    lot_address VARCHAR(1000),
    district VARCHAR(30),
    neighborhood VARCHAR(30),
    location VARBINARY,
    phone VARCHAR(50),
    website VARCHAR(1000),
    description VARCHAR(4000),
    image_url VARCHAR(4000),
    image_source VARCHAR(30),
    image_attribution VARCHAR(4000),
    operating_hours_raw VARCHAR(4000),
    operating_days_raw VARCHAR(4000),
    closed_days_raw VARCHAR(4000),
    transit_info VARCHAR(4000),
    accessibility VARCHAR(4000),
    tags VARCHAR ARRAY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS place_trend_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    aliases VARCHAR ARRAY,
    unique_posts INTEGER NOT NULL,
    unique_authors INTEGER NOT NULL,
    unique_queries INTEGER NOT NULL,
    unique_intent_categories INTEGER NOT NULL,
    collection_days INTEGER NOT NULL,
    recent_observed_posts INTEGER NOT NULL,
    average_observed_rank DOUBLE,
    first_observed_at TIMESTAMP WITH TIME ZONE,
    latest_observed_at TIMESTAMP WITH TIME ZONE,
    ad_suspected_ratio DOUBLE NOT NULL,
    minimum_evidence_passed BOOLEAN NOT NULL,
    watch_signal_count INTEGER NOT NULL,
    trend_available BOOLEAN NOT NULL,
    trend_rising BOOLEAN NOT NULL,
    trend_ratio DOUBLE,
    recent_trend_value DOUBLE,
    previous_trend_value DOUBLE,
    recent_nonzero_observations INTEGER,
    baseline_nonzero_observations INTEGER,
    trend_reason VARCHAR(80),
    trend_checked_at TIMESTAMP WITH TIME ZONE,
    semantics VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS filming_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    content_type VARCHAR(30),
    match_status VARCHAR(30)
);
